# Generated by Django 5.2.9 on 2026-01-04 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало парсинга')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершение')),
                ('total_found', models.IntegerField(default=0, verbose_name='Найдено вакансий')),
                ('new_vacancies', models.IntegerField(default=0, verbose_name='Новых вакансий')),
                ('updated_vacancies', models.IntegerField(default=0, verbose_name='Обновлено')),
                ('errors', models.TextField(blank=True, null=True, verbose_name='Ошибки')),
                ('status', models.CharField(choices=[('running', 'В процессе'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='running', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Лог парсинга',
                'verbose_name_plural': 'Логи парсинга',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hh_id', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='ID на HH.ru')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Название вакансии')),
                ('company_name', models.CharField(max_length=255, verbose_name='Компания')),
                ('company_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на компанию')),
                ('description', models.TextField(verbose_name='Описание')),
                ('salary_from', models.PositiveIntegerField(blank=True, null=True, verbose_name='Зарплата от')),
                ('salary_to', models.PositiveIntegerField(blank=True, null=True, verbose_name='Зарплата до')),
                ('currency', models.CharField(default='RUR', max_length=5, verbose_name='Валюта')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Город')),
                ('experience', models.CharField(blank=True, max_length=50, null=True, verbose_name='Требуемый опыт')),
                ('employment', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип занятости')),
                ('schedule', models.CharField(blank=True, max_length=50, null=True, verbose_name='График работы')),
                ('url', models.URLField(verbose_name='Ссылка на вакансию')),
                ('skills', models.JSONField(blank=True, default=list, verbose_name='Требуемые навыки')),
                ('published_at', models.DateTimeField(verbose_name='Дата публикации на HH')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено в БД')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='VacancyNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
                ('is_viewed', models.BooleanField(default=False, verbose_name='Просмотрено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Пользователь')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Уведомление о вакансии',
                'verbose_name_plural': 'Уведомления о вакансиях',
                'ordering': ['-sent_at'],
                'unique_together': {('user', 'vacancy')},
            },
        ),
        migrations.AddField(
            model_name='vacancy',
            name='notified_users',
            field=models.ManyToManyField(related_name='notified_vacancies', through='vacancies.VacancyNotification', to='users.user', verbose_name='Уведомленные пользователи'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['-published_at'], name='vacancies_v_publish_38d5cd_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['is_active', '-published_at'], name='vacancies_v_is_acti_6f1a80_idx'),
        ),
    ]
