# Generated by Django 5.2.9 on 2026-01-05 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_employmenttype_options_alter_stack_options_and_more'),
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено в избранное')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки пользователя')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_vacancies', to='users.user', verbose_name='Пользователь')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='vacancies.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Избранная вакансия',
                'verbose_name_plural': 'Избранные вакансии',
                'ordering': ['-added_at'],
                'unique_together': {('user', 'vacancy')},
            },
        ),
        migrations.CreateModel(
            name='VacancyReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('like', 'Интересно'), ('dislike', 'Не подходит')], max_length=10, verbose_name='Реакция')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата реакции')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_reactions', to='users.user', verbose_name='Пользователь')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='vacancies.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Реакция на вакансию',
                'verbose_name_plural': 'Реакции на вакансии',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'vacancy')},
            },
        ),
    ]
