# Generated by Django 5.2.9 on 2026-01-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_favoritevacancy_vacancyreaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancynotification',
            name='viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
