# Generated by Django 5.2.9 on 2026-01-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_vacancynotification_viewed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='employment',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Тип занятости'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='experience',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Требуемый опыт'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='hh_id',
            field=models.CharField(db_index=True, max_length=250, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='published_at',
            field=models.DateTimeField(verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='schedule',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='График работы'),
        ),
    ]
