# Generated by Django 5.2.9 on 2026-01-19 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_employmenttype_options_alter_stack_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_text', models.TextField(help_text='Извлечённый и нормализованный текст резюме, полученный от бота', verbose_name='Resume text')),
                ('result', models.JSONField(blank=True, help_text='Результат AI-анализа резюме: сильные стороны, слабые места и рекомендации', null=True, verbose_name='AI analysis result')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', help_text='Текущий статус процесса AI-анализа', max_length=20, verbose_name='Analysis status')),
                ('error', models.TextField(blank=True, help_text='Текст ошибки, если анализ завершился неуспешно', verbose_name='Error message')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания запроса на анализ резюме', verbose_name='Created at')),
                ('user', models.ForeignKey(help_text='Пользователь, запросивший AI-анализ резюме', on_delete=django.db.models.deletion.CASCADE, related_name='resume_analyses', to='users.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Resume analysis',
                'verbose_name_plural': 'Resume analyses',
                'db_table': 'resume_analysis',
                'ordering': ('-created_at',),
            },
        ),
    ]
