# Generated by Django 5.2.9 on 2026-01-07 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_employmenttype_options_alter_stack_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Сообщение, отправленное пользователем через команду /comment', verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания комментария', verbose_name='Дата создания')),
                ('user', models.ForeignKey(help_text='Пользователь, оставивший комментарий в боте', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'db_table': 'comment',
                'ordering': ['-created_at'],
            },
        ),
    ]
