# Generated by Django 5.1.5 on 2026-01-01 13:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=50, verbose_name='Title / Название')),
            ],
            options={
                'verbose_name': 'Employment type / Тип занятости',
                'verbose_name_plural': 'Employment types / Типы занятости',
            },
        ),
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Technology / Технология')),
            ],
            options={
                'verbose_name': 'Stack / Стек',
                'verbose_name_plural': 'Stacks / Стеки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=50, verbose_name='Title / Название')),
            ],
            options={
                'verbose_name': 'Work format / Формат работы',
                'verbose_name_plural': 'Work formats / Форматы работы',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Username / Ник')),
                ('role', models.CharField(db_index=True, max_length=50, verbose_name='Role / Роль')),
                ('level', models.CharField(blank=True, choices=[('junior', 'Junior / Джуниор'), ('middle', 'Middle / Мидл'), ('senior', 'Senior / Сеньор'), ('lead', 'Lead / Лид')], max_length=10, null=True, verbose_name='Level / Уровень')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Location / Локация')),
                ('salary_from', models.PositiveIntegerField(blank=True, null=True, verbose_name='Salary from / Зарплата от')),
                ('currency', models.CharField(default='USD', max_length=5, verbose_name='Currency / Валюта')),
                ('notify_mode', models.CharField(choices=[('instant', 'Instant / Сразу'), ('daily', 'Daily / Ежедневно'), ('weekly', 'Weekly / Еженедельно')], default='daily', max_length=10, verbose_name='Notification mode / Уведомления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active / Активен')),
                ('is_profile_completed', models.BooleanField(default=False, verbose_name='Profile completed / Профиль заполнен')),
                ('onboarding_step', models.CharField(blank=True, max_length=50, null=True, verbose_name='Onboarding step / Шаг онбординга')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at / Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at / Обновлён')),
                ('employment_types', models.ManyToManyField(blank=True, related_name='users', to='users.employmenttype', verbose_name='Employment types / Типы занятости')),
                ('stack', models.ManyToManyField(blank=True, related_name='users', to='users.stack', verbose_name='Tech stack / Стек технологий')),
                ('work_formats', models.ManyToManyField(blank=True, related_name='users', to='users.workformat', verbose_name='Work formats / Форматы работы')),
            ],
            options={
                'verbose_name': 'User / Пользователь',
                'verbose_name_plural': 'Users / Пользователи',
                'ordering': ['-created_at'],
            },
        ),
    ]
