# Generated by Django 5.2.9 on 2026-01-05 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employmenttype',
            options={'ordering': ['title'], 'verbose_name': 'Тип занятости', 'verbose_name_plural': 'Типы занятости'},
        ),
        migrations.AlterModelOptions(
            name='stack',
            options={'ordering': ['name'], 'verbose_name': 'Стек', 'verbose_name_plural': 'Стеки'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='workformat',
            options={'ordering': ['title'], 'verbose_name': 'Формат работы', 'verbose_name_plural': 'Форматы работы'},
        ),
    ]
