# Generated by Django 5.1.3 on 2026-01-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название канала')),
                ('channel_id', models.BigIntegerField(unique=True, verbose_name='ID канала')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username канала')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Обязательный канал',
                'verbose_name_plural': 'Обязательные каналы',
            },
        ),
    ]
