# Generated by Django 5.2.9 on 2026-01-05 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requiredchannel',
            options={'ordering': ['title'], 'verbose_name': 'Обязательный канал', 'verbose_name_plural': 'Обязательные каналы'},
        ),
    ]
