# Generated by Django 5.2.9 on 2026-01-05 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broadcastprompt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broadcastmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Сообщение рассылки', 'verbose_name_plural': 'Сообщение рассылки'},
        ),
    ]
